name: inception

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb_container
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb-data:/var/lib/mysql

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress_container
    restart: always
    env_file:
      - .env
    volumes:
      - wp-data:/var/www/html

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx_container
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html

  redis:
    depends_on:
      - nginx
    build: ./requirements/bonus/redis
    image: redis:inception
    container_name: redis_container
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"

  ftp:
    depends_on:
      - nginx
    build: ./requirements/bonus/FTP
    image: ftp:inception
    container_name: ftp_container
    restart: always
    env_file:
      - .env
    ports:
      - "21:21" # control
      - "20:20" # data active
      - "21100-21110:21100-21110" # data passive
    volumes:
      - wp-data:/var/www/html

  static_website:
    build: ./requirements/bonus/static-website
    image: static_website:inception
    container_name: static_website_container
    restart: always
    ports:
      - "8080:80"

  adminer:
    depends_on:
      - mariadb
    build: ./requirements/bonus/adminer
    image: adminer:inception
    container_name: adminer_container
    restart: always
    ports:
      - "8081:8081"

volumes:
  wp-data:
    driver: local # Store data on the local machine (not remote storage like NFS or cloud)
    driver_opts: # driver options
      type: none # Don’t use any special filesystem type (like ext4, nfs, etc.)
      o: bind # Bind (attach) this volume to an existing directory on the host
      device: /home/mdahani/data/wordpress-data # This is where data will physically be stored.
  mariadb-data:
    driver: local # Store data on the local machine (not remote storage like NFS or cloud)
    driver_opts: # driver options
      type: none # Don’t use any special filesystem type (like ext4, nfs, etc.)
      o: bind # Bind (attach) this volume to an existing directory on the host
      device: /home/mdahani/data/mariadb-data # This is where data will physically be stored.
